export { MainIcon } from './icons/Main'
export { SearchIcon } from './icons/Search'
export { PeopleIcon } from './icons/People'
export { MenuIcon } from './icons/Menu'
export { RightArrow } from './icons/RighArrow'