export { WhtspIcon } from "./WhtspIcon";
export { TgIcon } from "./TgIcon";
export { VkIcon } from "./VkIcon";
export { YtIcon } from "./YtIcon";
export { WebSiteIcon } from "./WebSiteIcon";
export { YndDzenIcon } from "./YndDzenIcon";
export { PhoneIcon } from "./PhoneIcon";
export { EmailIcon } from "./EmailIcon";
export { AddressIcon } from "./AddressIcon";