export { NewsCardSmall } from "./ui/NewsCardSmall"
export { NewsCardBig } from "./ui/NewsCardBig"
export { NewsContent } from "./ui/NewsContent"
export type { NewsItem } from "./model/types/news.types"
export { getNews } from "./model/api/getNews"
export { getNewsById } from "./model/api/getNewsById"
export { getUniqueBadgesFromNews } from "./model/lib/getUniqueBadgesFromNews"